### PR TITLE
bug(aws): root block device calculation - autoscaling launch template.

### PR DESCRIPTION
**Pull request by NeverovDS**
Issue #625

### CODE REVIEW

**Comment by NeverovDS** [comment]
@ekifel check plz

**Comment by ekifel** [comment]
@alikhajeh1 LGTM, but can u take a quick look? I'm not 100% sure that we understand issue point correctly

**Comment by alikhajeh1** [comment]
@robh007 if you get the chance, it would be great if you can take a quick look at this to see if it addresses the issue you created.

**Comment by alikhajeh1** [comment]
I think this makes sense as aws_eks_node_group also uses launch_templates. Going to merge this but happy to change it if @robh007 says otherwise!

**Pull request merged**
