### PR TITLE
Docs: update add resources guide to reference new regions 

### PR DESCRIPTION
**Pull request by hugorut**
* Adds further details to `Region Usage` section highlighting how to add new regions
* Fixes bug with google cloud share region usage schema which had incorrect keys

### CODE REVIEW

**Comment by hugorut** [comment]
@aliscott thought it best to add in some docs about this process. However, with the automated alerts we'll hopefully keep on top of it.

**Review by aliscott — APPROVED** [review]
Good idea

**Comment by alikhajeh1** [comment]
@hugorut is the new AWS region going live after v0.9.16?

**Comment by hugorut** [comment]
> @hugorut is the new AWS region going live after v0.9.16?

@alikhajeh1 yup - see https://github.com/infracost/infracost/pull/1236

**Comment by hugorut** [comment]
@alikhajeh1 also added new automated region checking - https://github.com/infracost/infracost/actions/workflows/check-resources.yml

**Comment by alikhajeh1** [comment]
Awesome, I saw those but wondered if the Cloud Pricing API also needed an update

**Comment by hugorut** [comment]
@alikhajeh1 no it's all good 👍

**Comment by alikhajeh1** [comment]
🥇

**Comment by aliscott** [comment]
@hugorut is this good to merge now?

**Comment by hugorut** [comment]
Whoops, not sure why this isn't merged

**Pull request merged**
