### PR TITLE
Add support for RDS Cluster Replicated Write I/O charges

### PR DESCRIPTION
**Pull request by jwsz-capco**
* Add RDSCluster parameter for MonthlyReplicatedWrite count
* Add `monthly_replicated_write` to `RDSClusterUsageSchema` variable

### CODE REVIEW

**Comment by aliscott** [comment]
Thanks @jwsz-capco 🙏! Let us know when this is ready for review.

**Comment by jwsz-capco** [comment]
Linked issue - #1374

**Comment by jwsz-capco** [comment]
@aliscott This is ready for review, I'm also expecting to sign a license before this can be merged - please could you forward the link? Thanks

**Comment by aliscott** [comment]
@jwsz-capco [here's the link](https://cla-assistant.io/infracost/infracost?pullRequest=1569), thanks!

**Review by aliscott — COMMENTED** [review]
Thanks for picking this up @jwsz-capco 🙏. It looks like this needs a few more things before it will work.

1. It needs a cost component that finds the price and uses the usage number from the usage file as the quantity. [Here's an example](https://github.com/infracost/infracost/blob/master/internal/resources/aws/rds_cluster.go#L113-L133) of this in the RDS resource for the snapshot export.

2. It should have an example in the infracost-usage-example.yml file [similar to this](https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml#L277).

3. I'd consider calling this `monthly_replicated_write_io_requests` to be consistent with other resources (cc @tim775 in case he disagrees).

Feel free to reach out here on on our [community slack](https://infracost.io/community-chat) if we can help in any way.

**Comment by alikhajeh1** [comment]
@jwsz-capco thank you for signing the CLA. Do you think you'll have time to finish this PR in June?

**Comment by jwsz-capco** [comment]
Hi @alikhajeh1 - I'll aim to get this done in June, sorry for the delay!

**Comment by alikhajeh1** [comment]
Any update on this?

**Comment by aliscott** [comment]
@jwsz-capco any update on this? No worries if you don't think you'll get a chance,

**Pull request closed without merging**
