### PR TITLE
feat: show all projects in table of infracost comment

### PR DESCRIPTION
**Pull request by fatihtokus**
Closes https://github.com/infracost/infracost/issues/1538

### CODE REVIEW

**Comment by aliscott** [comment]
Thanks for taking this on @fatihtokus 🙏. Let us know when this is ready for review.

**Comment by fatihtokus** [comment]
@aliscott , it is ready for review but I don't know why tests are failing with no reason

**Comment by hugorut** [comment]
@fatihtokus it looks as though the test are failing because formatting outputs have got trapped into the golden file tests. e.g.:

```diff
-USAGE
+[1mUSAGE[0m
  infracost output [flags
```

Maybe try updating the tests again using `make ARGS=" -update" test` and see if that removes the formatting. I'll take a peek once it's resolved.

It would be ideal to get this into the next release. Thanks

**Comment by aliscott** [comment]
Thanks @fatihtokus, I've tried this out and this looks good. After looking through the usage help text, I've decided it's actually best to call this `--show-all-projects`, since it's more consistent with the flags we already have - we already have `--show-skipped. So I'll push a quick commit to rename this and get it merged for the next commit.

**Review by hugorut — APPROVED** [review]

**Pull request merged**
