### PR TITLE
Add support for region string variable

### LINKED ISSUE #183: Support variables for provider's region
We currently only support constant values for the provider region, e.g:
terraform:
```
provider "aws" {
  region = "us-west-2"
}
```

But we need to support:
```
variable "region" {
  type    = string
  default = "us-west-2"
}

provider "aws" {
  region = var.region
}
```

### PR DESCRIPTION
**Pull request by sinabakh**
Fix #183

### CODE REVIEW

**Comment by sinabakh** [comment]
@aliscott Adding support for string variable was a piece of a cake but I have some problems with other data types. As you can see in https://www.terraform.io/docs/configuration/variables.html there can be map variables. So let's say we have sth like this:
```
variable "nested_var" {
  type = map
  default = {
      "random_int" = 8300
      "random_region" = "us-east-1"
    }
}
provider "aws" {
  region                      = var.nested_var["region"]
  s3_force_path_style         = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  access_key                  = "mock_access_key"
  secret_key                  = "mock_secret_key"
}
```
I got this in plan json:
```json
{
  "format_version": "0.1",
  "terraform_version": "0.13.0",
  "variables": {
    "nested_var": {
      "value": {
        "random_int": "8300",
        "random_region": "us-east-1"
      }
    }
  },
  "planned_values": {
    "root_module": {}
  },
  "configuration": {
    "provider_config": {
      "aws": {
        "name": "aws",
        "expressions": {
          "access_key": {
            "constant_value": "mock_access_key"
          },
          "region": {
            "references": [
              "var.nested_var"
            ]
          },
          "s3_force_path_style": {
            "constant_value": true
          },
          "secret_key": {
            "constant_value": "mock_secret_key"
          },
          "skip_credentials_validation": {
            "constant_value": true
          },
          "skip_metadata_api_check": {
            "constant_value": true
          },
          "skip_requesting_account_id": {
            "constant_value": true
          }
        }
      }
    },
    "root_module": {
      "variables": {
        "nested_var": {
          "default": {
            "random_int": "8300",
            "random_region": "us-east-1"
          }
        }
      }
    }
  }
}
```
As you see there's no indication of the actual `random_region` in the region field. It just references the main object not it's nested field.

**Comment by aliscott** [comment]
@sinabakh yeah this is an issue, but it's okay for just now - with the current plan output there's nothing we can do.

**Comment by aliscott** [comment]
This looks great, thanks @sinabakh!

Just a general comment on go variable naming - for vars that are just used in the context of a function it's preferred to keep them short, e.g:
```
splittedReference -> splitRef / s
referenceName -> ref / refName
variableName -> varName
```

I'm still learning the go conventions myself, so thought it would be good to share this. Here's some useful reads:
 * https://github.com/golang/go/wiki/CodeReviewComments#variable-names
 * https://talks.golang.org/2014/names.slide#6

**Comment by sinabakh** [comment]
@aliscott Thanks for your suggestion, they were interesting links. I changed the namings, enhanced the logic and added some tests. It would be great if you can review it.

**Comment by aliscott** [comment]
Thanks @sinabakh looks great!

**Pull request merged**
