### PR TITLE
fix: add support for ZRS disks

### PR DESCRIPTION
**Pull request by grixxie**
Addressing issue: https://github.com/infracost/infracost/issues/2126

make managed_disk mappings no longer dependant on hardcoded replication types.

however, kubernetes_cluster_node_pool.aksOSDiskSubResource is still using Premium_LRS.

any feedback appreciated

### CODE REVIEW

**Comment by tim775** [comment]
Thanks @grixxie is this ready for review?

**Comment by grixxie** [comment]
Yes this is ready. I can see the above failing AWS integration tests are part of an existing issue which is a relief for me personally. Will mark as ready.

**Review by aliscott — CHANGES_REQUESTED** [review]
Hi @grixxie thank you for this PR. I apologise for the delay reviewing it. This looks almost good to go, but needs a few changes to get the right prices from the pricing API. I'm seeing a few issues when running the Azure tests locally. These don't run by default for forks since they require Azure creds, but you can run them locally running:

```sh
az login
make test_azure
```

**Comment by grixxie** [comment]
Thanks for this @aliscott . I have implemented your suggestions. I hadn't run the Azure tests until you mentioned it - I get errors too but I think mine are probably to do with some misconfiguration on my local as i still get errors after reverting my original change.

**Review by aliscott — APPROVED** [review]
Thanks @grixxie, this looks great 🙏. I've pushed a commit just to update the test snapshots.

**Comment by grixxie** [comment]
Great, thanks for this @aliscott. Do you know when this will be released? what is the process?

**Comment by tim775** [comment]
@grixxie this is live in v0.10.16.  Thanks again.

**Comment by alikhajeh1** [comment]
@grixxie as a small thank you gift, we'd like to send you [InfraSocks](https://twitter.com/AliKhajeh/status/1510310791508946945) - I couldn't find your email address so can you possibly email me at ali.hosseini@infracost.io so I can send you a link?

**Pull request merged**
