### PR TITLE
Fix case comparisons for gcp

### PR DESCRIPTION
**Pull request by krishnaindani**
- This is one of the PR to fix https://github.com/infracost/infracost/issues/729. This takes care of fixing the case comparison for the google cloud.

### CODE REVIEW

**Comment by krishnaindani** [comment]
@alikhajeh1 can you approve running the workflow? I have test passing locally for google.

**Comment by alikhajeh1** [comment]
Done! I'm watching the Euro 2020 football games just now but will keep an eye on this to re-click on Approve when needed 😅 

`make test_google` can be run locally if you want faster iteration time

**Comment by krishnaindani** [comment]
> Done! I'm watching the Euro 2020 football games just now but will keep an eye on this to re-click on Approve when needed 😅
> 
> `make test_google` can be run locally if you want faster iteration time

I have tested locally those are passing. Enjoy the game, I guess this can wait.

**Comment by krishnaindani** [comment]
The tests look good.

**Comment by alikhajeh1** [comment]
Thanks @krishnaindani! Can you please check the following warnings from the test outputs? I suspect some tweaks might be needed as [the latest master branch run](https://github.com/infracost/infracost/runs/2964690587) doesn't have these warnings.

```
=== CONT  TestNewSQLInstance
time="2021-07-02T17:27:58Z" level=warning msg="Multiple products found for google_storage_bucket.EuMulti Object adds, bucket/object list (class A), using the first product"
time="2021-07-02T17:27:58Z" level=warning msg="Multiple products found for google_storage_bucket.EuMulti Object gets, retrieve bucket/object metadata (class B), using the first product"
time="2021-07-02T17:27:58Z" level=warning msg="Multiple products found for google_storage_bucket.non_usage Object adds, bucket/object list (class A), using the first product"
time="2021-07-02T17:27:58Z" level=warning msg="Multiple products found for google_storage_bucket.non_usage Object gets, retrieve bucket/object metadata (class B), using the first product"

=== CONT  TestContainerRegistryGoldenFile
time="2021-07-02T17:28:41Z" level=warning msg="Multiple products found for google_container_registry.my_registry Object adds, bucket/object list (class A), using the first product"
time="2021-07-02T17:28:41Z" level=warning msg="Multiple products found for google_container_registry.my_registry Object gets, retrieve bucket/object metadata (class B), using the first product"
--- PASS: TestContainerRegistryGoldenFile (5.37s)
```

**Comment by krishnaindani** [comment]
> Thanks @krishnaindani! Can you please check the following warnings from the test outputs? I suspect some tweaks might be needed as [the latest master branch run](https://github.com/infracost/infracost/runs/2964690587) doesn't have these warnings.
> 
> ```
> === CONT  TestNewSQLInstance
> time="2021-07-02T17:27:58Z" level=warning msg="Multiple products found for google_storage_bucket.EuMulti Object adds, bucket/object list (class A), using the first product"
> time="2021-07-02T17:27:58Z" level=warning msg="Multiple products found for google_storage_bucket.EuMulti Object gets, retrieve bucket/object metadata (class B), using the first product"
> time="2021-07-02T17:27:58Z" level=warning msg="Multiple products found for google_storage_bucket.non_usage Object adds, bucket/object list (class A), using the first product"
> time="2021-07-02T17:27:58Z" level=warning msg="Multiple products found for google_storage_bucket.non_usage Object gets, retrieve bucket/object metadata (class B), using the first product"
> 
> === CONT  TestContainerRegistryGoldenFile
> time="2021-07-02T17:28:41Z" level=warning msg="Multiple products found for google_container_registry.my_registry Object adds, bucket/object list (class A), using the first product"
> time="2021-07-02T17:28:41Z" level=warning msg="Multiple products found for google_container_registry.my_registry Object gets, retrieve bucket/object metadata (class B), using the first product"
> --- PASS: TestContainerRegistryGoldenFile (5.37s)
> ```

sure. Will check on that.

**Comment by krishnaindani** [comment]
> > Thanks @krishnaindani! Can you please check the following warnings from the test outputs? I suspect some tweaks might be needed as [the latest master branch run](https://github.com/infracost/infracost/runs/2964690587) doesn't have these warnings.
> > ```
> > === CONT  TestNewSQLInstance
> > time="2021-07-02T17:27:58Z" level=warning msg="Multiple products found for google_storage_bucket.EuMulti Object adds, bucket/object list (class A), using the first product"
> > time="2021-07-02T17:27:58Z" level=warning msg="Multiple products found for google_storage_bucket.EuMulti Object gets, retrieve bucket/object metadata (class B), using the first product"
> > time="2021-07-02T17:27:58Z" level=warning msg="Multiple products found for google_storage_bucket.non_usage Object adds, bucket/object list (class A), using the first product"
> > time="2021-07-02T17:27:58Z" level=warning msg="Multiple products found for google_storage_bucket.non_usage Object gets, retrieve bucket/object metadata (class B), using the first product"
> > 
> > === CONT  TestContainerRegistryGoldenFile
> > time="2021-07-02T17:28:41Z" level=warning msg="Multiple products found for google_container_registry.my_registry Object adds, bucket/object list (class A), using the first product"
> > time="2021-07-02T17:28:41Z" level=warning msg="Multiple products found for google_container_registry.my_registry Object gets, retrieve bucket/object metadata (class B), using the first product"
> > --- PASS: TestContainerRegistryGoldenFile (5.37s)
> > ```
> 
> sure. Will check on that.

will the tests need to be tweaked here?

**Comment by alikhajeh1** [comment]
Nope, it looks like the updated filters are causing multiple prices to be returned so maybe start with finding which filters they are. We can then see what the issue is with those filters.

**Comment by alikhajeh1** [comment]
oops, clicked on the wrong button

**Comment by krishnaindani** [comment]
> Nope, it looks like the updated filters are causing multiple prices to be returned so maybe start with finding which filters they are. We can then see what the issue is with those filters.

gotcha, that makes sense. Thanks

**Comment by krishnaindani** [comment]
I have reverted one place for regex comparisons where it was warning out. Tested locally for don't see warnings now. Maybe you can trigger build one more time to see how it goes.

**Comment by alikhajeh1** [comment]
Thanks @krishnaindani!

**Comment by krishnaindani** [comment]
> Thanks @krishnaindani!

Thank you @alikhajeh1 . Should I delete the branch to keep the repo clean since it is merged, or do we prefer to keep it?

**Comment by alikhajeh1** [comment]
The branch is in your fork of the repo so up to you :) I usually delete after merge

**Comment by krishnaindani** [comment]
> The branch is in your fork of the repo so up to you :) I usually delete after merge

yeah, didn't realize that's in my fork. Thanks

**Pull request merged**
