### PR TITLE
Add support for Bitbucket Server

### PR DESCRIPTION
**Pull request by wahlfeld10x**
Addresses: #1231

### CODE REVIEW

**Comment by alikhajeh1** [comment]
@wahlfeld10x any chance you can [sign the CLA](https://cla-assistant.io/infracost/infracost?pullRequest=1269)? That link has a "Human-friendly summary" - it's mainly to make it clear that we have permission to use your contribution.

**Comment by wahlfeld10x** [comment]
Yup, just waiting on our legal team to have a review, I've reached out to them again for an update. Apologies for the delay.
________________________________

**Comment by wahlfeld10x** [comment]
Alright, we're all good to go on our side!

**Review by hugorut — APPROVED** [review]
LGTM

**Comment by hugorut** [comment]
@wahlfeld10x we've got a lot of big changes into the next release so I'll hold off merging this until we're past the release at the end of the week. Thanks for your hard work 🥇

**Comment by vdmgolub** [comment]
This is live in v0.9.18. We also released a new `infracost comment bitbucket --help` command that supports both Bitbucket Cloud and Server, thank you @wahlfeld10x for the help! Please try it out, maybe you'll find it more convenient than the script :)

**Comment by alikhajeh1** [comment]
@wahlfeld10x we'd like to send you [InfraSocks](https://twitter.com/PeterDaveHello/status/1490679046673690625) as a small thank you gift for helping the community. If you'd like this, please email your postal address to ali.hosseini@infracost.io 🧦

**Pull request merged**
