### PR TITLE
Adding docs for requested docker image

### PR DESCRIPTION
**Pull request by sashman**

### CODE REVIEW

**Comment by alikhajeh1** [comment]
thanks @sashman! can you please check the 2 comments in https://github.com/infracost/infracost/pull/141 ? If those are done here, I can close #141 and merge this.

**Comment by alikhajeh1** [comment]
I suppose a similar thing should be done to https://github.com/infracost/docs/blob/master/docs/getting_started.md ?

**Comment by sashman** [comment]
Ah my bad, I didn't see this

**Comment by alikhajeh1** [comment]
Closing this as https://github.com/infracost/infracost#installation has been updated

**Pull request closed without merging**
