### PR TITLE
chore(docs): add homebrew installation

### LINKED ISSUE #73: Homebrew support
FYI, I have filed a pending PR for adding this utility into homebrew-core, https://github.com/Homebrew/homebrew-core/pull/60777

Thanks!

### PR DESCRIPTION
**Pull request by chenrui333**
relates to https://github.com/Homebrew/homebrew-core/pull/60777

fixes #73

### CODE REVIEW

**Comment by alikhajeh1** [comment]
Thanks @chenrui333, I'm watching https://github.com/Homebrew/homebrew-core/pull/60777 and will merge this and https://github.com/infracost/docs/pull/6 when that goes live.

**Comment by chenrui333** [comment]
@alikhajeh1 the homebrew-core PR is merged, I think we can go with a merge on this PR now. Thanks!

**Comment by alikhajeh1** [comment]
Seeing `brew install infracost` work just made my day @chenrui333 - thank you!

**Comment by alikhajeh1** [comment]
@chenrui333 is there a way we could push new versions of infracost to brew via https://github.com/infracost/infracost/blob/master/.github/workflows/create-release.yml ? I'm not at all pushing you to do it, just wondered if there's a best-practice or easy method that we should look at.

**Pull request merged**
