### PR TITLE
Add support for on-demand DynamoDB

### LINKED ISSUE #83: Add support for on-demand DynamoDB
Add support for on-demand DynamoDB by using usage data support based on infracost's terraform provider.

### PR DESCRIPTION
**Pull request by sinabakh**
**Status:**

- [x] Read and write requests
- [x] Data storage
- [x] Continuous backup
- [x] On-demand backup
- [x] Restore from backup
- [x] On-demand global tables
- [x] DynamoDB Streams

**Issues:**
- Fixes #83 

Useful links:
- Overview: https://aws.amazon.com/dynamodb/
- Pricing: https://aws.amazon.com/dynamodb/pricing/on-demand/
- Terraform: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table

### CODE REVIEW

**Comment by sinabakh** [comment]
@aliscott This PR is almost done, but I couldn't find anything related to data-transfre pricing in our pricing-api for DynamoDB. Could you also check it?

**Comment by aliscott** [comment]
Thanks @sinabakh. I'd ignore data transfer costs just now - they are aggregated across different services, so it's a separate resource we'll somehow need to model and add support for.

**Comment by sinabakh** [comment]
@aliscott So I think it's ready for review.

**Comment by alikhajeh1** [comment]
@sinabakh this is awesome. 

Given that we now have a "price" column, in addition to "cost" columns, we could show the price for PAY_PER_REQUEST dynamo tables, and leave the costs as blank. As a developer, I still find it valuable to see what has a price and what does not, and if I want, I could use the infracost terraform provider to add usage estimates to get cost estimates. It seems like some of the cost component names are similar to, e.g. `Write capacity unit (WCU)` vs `Write request units`, so the pricing is similar, it's just how the resources are "reserved" or "pre-provisioned". What do you think?

**Comment by sinabakh** [comment]
@alikhajeh1 I didn't exactly get what you mean by leaving the cost blank, the `PAY_PER_REQUEST` tables have cost and we calculate the price by using our own terraform plugin.

**Comment by alikhajeh1** [comment]
> @alikhajeh1 I didn't exactly get what you mean by leaving the cost blank, the `PAY_PER_REQUEST` tables have cost and we calculate the price by using our own terraform plugin.

I'm probably missing something @sinabakh, can you please paste the output when the infracost terraform provider isn't used? I'm working on https://github.com/infracost/infracost/pull/113/files#diff-6a3371457528722a734f3c51d9238c13R15-R50 that should help clarify what can work nicely when adding new resources.

In my mind, the infracost terraform provider is still not validated with users and we don't know if developers will take the extra step of adding that to their terraform, so I want to ensure that going forward we show all price components regardless of that provider being used or not. Just seeing that something has a price has value, and that should continue to work even if we change strategy to do something else for usage-based costs.

**Comment by sinabakh** [comment]
@alikhajeh1 Oh I think I got what you mean,
currently with usage data with `PAY_PER_REQUEST` we got this:
```
  NAME                                                 MONTHLY QTY  UNIT         PRICE   HOURLY COST  MONTHLY COST

  aws_dynamodb_table.my_dynamodb_table
  ├─ Continuous backup (PITR) storage                         2300  GB-months    0.2000       0.6301      460.0000
  ├─ Data storage                                              230  GB-months    0.2500       0.0788       57.5000
  ├─ On-demand backup storage                                  460  GB-months    0.1000       0.0630       46.0000
  ├─ Read request unit (RRU)                               8000000  RRU-months    2e-07       0.0027        2.0000
  ├─ Restore data size                                         230  GB-months    0.1500       0.0473       34.5000
  ├─ Streams read request unit (sRRU)                      2000000  sRRU-months   2e-07       0.0005        0.4000
  ├─ Write request unit (WRU)                              3000000  WRU-months    1e-06       0.0051        3.7500
  ├─ Replicated write request unit (rWRU) (us-east-2)      3000000  rWRU-months   2e-06       0.0077        5.6250
  └─ Replicated write request unit (rWRU) (us-west-1)      3000000  rWRU-months   2e-06       0.0086        6.2739
  Total                                                                                       0.8439      616.0489

  OVERALL TOTAL                                                                               0.8439      616.0489
```
And without usage data:
```
  NAME                                  MONTHLY QTY  UNIT  PRICE  HOURLY COST  MONTHLY COST

  aws_dynamodb_table.my_dynamodb_table
  Total                                                                0.0000        0.0000

  OVERALL TOTAL                                                        0.0000        0.0000
```

I think you mean we show costs for basic resources but with no price. Like read/write request units.

**Comment by alikhajeh1** [comment]
@sinabakh yep, I'll merge this as it predates https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md and I'll add a ticket so we change it to always show the price, but only cost if the terraform provider is used.

**Pull request merged**
