### PR TITLE
fix(azure): case comparison

### PR DESCRIPTION
**Pull request by krishnaindani**
PR to fix case comparisons for Azure
Issue: https://github.com/infracost/infracost/issues/729

### CODE REVIEW

**Comment by krishnaindani** [comment]
@alikhajeh1 I see in the azure tests are not running here https://github.com/infracost/infracost/runs/2992930511?check_suite_focus=true? Does someone need to take any actions there to run? Also see most of the comparisons in Azure are done in a string case insensitive way, so that's a good thing.

**Comment by krishnaindani** [comment]
One more thing, in General guidelines I already see it mentions to use string case insensitive comparisons, so I guess it's already updated. https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#general-guidelines (on the last bullet point)

**Comment by alikhajeh1** [comment]
@krishnaindani we only run the azure tests on the master branch updates as they need cloud creds (which we can't set in the PR sender's fork). They were fine on my machine so I merged this so I merged this and we'll see if there are any issues in [this](https://github.com/infracost/infracost/runs/2996456349). 

Contributing guide was updated a while ago, that's why the Azure resources were mostly ok :)

**Comment by krishnaindani** [comment]
> this

gotcha, that makes sense. Thanks

**Comment by krishnaindani** [comment]
> @krishnaindani we only run the azure tests on the master branch updates as they need cloud creds (which we can't set in the PR sender's fork). They were fine on my machine so I merged this so I merged this and we'll see if there are any issues in [this](https://github.com/infracost/infracost/runs/2996456349).
> 
> Contributing guide was updated a while ago, that's why the Azure resources were mostly ok :)

gotcha, that makes sense. Thanks

**Pull request merged**
