### PR TITLE
Add support for EKS clusters

### LINKED ISSUE #82: Add support for EKS clusters

### PR DESCRIPTION
**Pull request by m-yosefpor**
**Objective:**

Add support for `aws_eks_node_group`

**Example output:**

// TODO
  
**Pricing details:**

//TODO

**Status:**

- [x] Added to resource_registry.go
- [ ] Added resource file
- [ ] Added integration tests
- [x] Added unit tests if applicable - Not applicable
- [x] Added to https://github.com/infracost/docs/blob/master/docs/supported_resources.md
        see https://github.com/infracost/docs/pull/9

**Issues:**

Closes #82 

**Useful links:**

- Pricing: https://aws.amazon.com/eks/pricing/
- Terraform: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group

### CODE REVIEW

**Comment by m-yosefpor** [comment]
This resource has a block like this:
```
scaling_config {
    desired_size = 2
    max_size     = 3
    min_size     = 1
  }
```
For now I should only consider `desirde_size`, like we did for `aws_autoscaling_group` yeah?

**Comment by alikhajeh1** [comment]
@m-yosefpor any update on this? I'd be happy to take it if you're ok with that?

**Comment by m-yosefpor** [comment]
Oh sorry I've forgot about it.. I'll finish it this weekend

**Comment by alikhajeh1** [comment]
@m-yosefpor as discussed, @sashman has kindly offered to take https://github.com/infracost/infracost/issues/82, so I'll close this.

**Pull request closed without merging**
