### PR TITLE
fix: error on missing usage file when sync-usage-file not in use

### PR DESCRIPTION
**Pull request by cjdalan**
Fixes: https://github.com/infracost/infracost/issues/1574

### CODE REVIEW

**Comment by hugorut** [comment]
hi @cjdalan thanks for the PR. I agree it's a bit weird to fail silently here - let me check in with the team to see what was the original reasoning behind this. Also my initial thought is we might want to throw a `WARN` the user and not fail explicitly.

**Comment by hugorut** [comment]
; I, I wasn't aware of https://github.com/infracost/infracost/issues/1574. Thanks for raising this PR. There are a few lint errors to fix; this looks like they might be originating from tests or other parts of the application where you haven't updated the caller to use the new function signature. If you have a crack at fixing those, I'll give this a once over, and we can merge it.

**Comment by cjdalan** [comment]
i have some errors when running `make lint` unrelated to my changes:
```
golangci-lint run
WARN [linters context] bodyclose is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649. 
WARN [linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649. 
internal/hcl/attribute.go:617:5: SA4004: the surrounding loop is unconditionally terminated (staticcheck)
                                break
                                ^
internal/apiclient/auth.go:69:4: S1037: should use time.Sleep instead of elaborate way of sleeping (gosimple)
                        select {
                        ^
internal/apiclient/auth.go:68:3: S1000: should use for range instead of for { select {} } (gosimple)
                for {
                ^
make: *** [lint] Error 1
```

**Comment by hugorut** [comment]
@cjdalan  hmm I'm not seeing that on my `lint` it might be because you have a different version of `golangci-lint` locally then what we use on ci. I'm seeing some test errors now. Could you resolve these? 

Quick tip, you can run the test suite locally using `make test` and then for a specific cloud vendor using a suffix, eg: `make test_aws`. You can read more about setting up the development environment in our contributing guide, [here](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#setting-up-the-development-environment).

**Comment by alikhajeh1** [comment]
@cjdalan any update on this?

**Pull request closed without merging**
