### PR TITLE
feat(Azure): Add support for case insensitive Azure VM sizes

### PR DESCRIPTION
**Pull request by mnaghavi**
Regarding [issue 1982](https://github.com/infracost/infracost/issues/1982), VM size in Azure needs to be case insensitive.

### CODE REVIEW

**Comment by mnaghavi** [comment]
@alikhajeh1 ready to review Ali jan.

**Comment by alikhajeh1** [comment]
Thanks @mnaghavi jaan! I assigned it to @vdmgolub since he reviewed the GH issue too

**Review by vdmgolub — APPROVED** [review]
Thank you, looks good! 👍 I've also added test coverage for the changes.

**Comment by mnaghavi** [comment]
> Thank you, looks good! 👍 I've also added test coverage for the changes.

Nice, thanks for adding the tests.

**Pull request merged**
