### PR TITLE
feat(scaleway): add scaleway

### PR DESCRIPTION
**Pull request by adnsio**
### WIP

Adds support to Scaleway.

PR open for comments. Cloud Pricing PR: https://github.com/infracost/cloud-pricing-api/pull/95

### CODE REVIEW

**Comment by alikhajeh1** [comment]
@adnsio should we close this PR for now until you/someone else has time to pick it up?

**Comment by adnsio** [comment]
@alikhajeh1 I'm sorry but I don't have enough free time to work on it anymore, if anyone wants they can continue it :(

**Comment by ch9hn** [comment]
Scaleway got a public pricing api - so it is quite simple to get all prices and updates from that.

For example:

https://api.scaleway.com/instance/v1/zones/<region>/products/servers

Example output for `region=nl-ams-1`:

```
{
   "servers":{
      "DEV1-L":{
         "alt_names":[
            
         ],
         "arch":"x86_64",
         "ncpus":4,
         "ram":8589934592,
         "gpu":0,
         "volumes_constraint":{
            "min_size":0,
            "max_size":80000000000
         },
         "per_volume_constraint":{
            "l_ssd":{
               "min_size":1000000000,
               "max_size":800000000000
            }
         },
         "baremetal":false,
         "monthly_price":36.1496,
         "hourly_price":0.04952,
         "capabilities":{
            "boot_types":[
               "bootscript",
               "rescue",
               "local"
            ],
            "default_boot_type":"local",
            "hot_snapshots_local_volume":true,
            "placement_groups":true,
            "block_storage":true,
            "private_network":8
         },
         "network":{
            "ipv6_support":true,
            "sum_internal_bandwidth":400000000,
            "sum_internet_bandwidth":400000000,
            "interfaces":[
               {
                  "internal_bandwidth":400000000,
                  "internet_bandwidth":null
               },
               {
                  "internal_bandwidth":null,
                  "internet_bandwidth":400000000
               }
            ]
         }
      },
```

**Comment by alessiodionisi** [comment]
@ch9hn thanks, I’ll take a look

**Pull request closed without merging**
