### PR TITLE
update terraform version on dockerfile to 0.14.2

### PR DESCRIPTION
**Pull request by bmbferreira**

### CODE REVIEW

**Comment by alikhajeh1** [comment]
@bmbferreira thanks for the PR! I wonder if we should do something similar to [atlantis](https://github.com/runatlantis/atlantis/blob/master/Dockerfile#L9-L20) for the latest versions of 0.12, 0.13 and 0.14 (the infracost [supported versions](https://www.infracost.io/docs/faq#what-terraform-versions-are-supported)) so users can use the [TERRAFORM_BINARY env](https://www.infracost.io/docs/#environment-variables) to override the default.

Also, if we do that, should the default be the latest stable version of terraform or kept as is to avoid breaking CI pipelines? This image is used in the [ci integrations](https://www.infracost.io/docs/integrations) too.

@aliscott any thoughts?

**Comment by aliscott** [comment]
> I wonder if we should do something similar to atlantis

Another option is to build images for each Terraform version to keep the image size smaller similar to how a lot of packages build for different versions of Alpine (like https://hub.docker.com/_/golang). For example:

`infracost:latest` - uses latest infracost and the latest Terraform
`infracost:v0.7.7` - uses infracost v0.7.7 and the latest Terraform
`infracost:latest-terraform0.14.2` - uses latest infracost and Terraform 0.14.2
`infracost:v0.7.7-terraform0.14.2` - uses infracost v0.7.7 and Terraform 0.14.2

**Comment by alikhajeh1** [comment]
TF 0.12.29 is 67M and 0.14.0 is 78M uncompressed on Linux, so this would add ~150MB to the current 140MB image (from `docker images` on centos, it's 60MB compressed on dockerhub). Doubling the image size isn't great, it slows down CI integrations that don't cache the image. I think we prefer it if users use the latest version of infracost with whatever version of TF they need, so the multiple images sounds good.

**Comment by alikhajeh1** [comment]
I'm going to merge this as I don't see any breaking changes in the [0.14.2 changelog](https://github.com/hashicorp/terraform/blob/v0.14.2/CHANGELOG.md). If required, we can continue the discussion on https://github.com/infracost/infracost/issues/57

**Comment by bmbferreira** [comment]
Hi @alikhajeh1! I'm really sorry for the late response! I think it is a good idea to have multiple images, however I can't promise at this moment that I can take ownership of doing that change right now. 😞  If I find the time I would like to do it. Thanks for merging the PR and for all your work. 🙇

**Comment by alikhajeh1** [comment]
@bmbferreira no problems at all, sorry that we kinda went overboard with the discussion on this 1-line simple change :)

**Pull request merged**
