### PR TITLE
test: Capture logs in golden file tests

### PR DESCRIPTION
**Pull request by tim775**
test(aws): Capture logs for aws golden file tests

### CODE REVIEW

**Comment by tim775** [comment]
Hey @sinabakh, any chance you have a moment to review?  I believe you suggested doing this a while ago 😉

**Comment by sinabakh** [comment]
@tim775 Nice! LGTM. However, I was thinking about the fact that if we add support for a missing resource then some tests will fail. Am I right?

**Comment by tim775** [comment]
>  However, I was thinking about the fact that if we add support for a missing resource then some tests will fail. Am I right?
Yeah that's true you would need to `-update` to fix any tests that break.  That doesn't seem like to big of a hassle and I guess it's expected since you really are changing what output is generated.

**Comment by sinabakh** [comment]
That makes sense. Thanks

**Pull request merged**
