### PR TITLE
Case comparison

### PR DESCRIPTION
**Pull request by krishnaindani**
This will fix all case comparisons in the provider's directory. 

Issue: https://github.com/infracost/infracost/issues/729

### CODE REVIEW

**Comment by krishnaindani** [comment]
@alikhajeh1 I have a pr mostly ready would like to see the workflow stages, which I can't run looks like. Would you be able to help?

**Comment by alikhajeh1** [comment]
@krishnaindani done, I'll keep an eye on this PR and keep clicking on the Approve workflow, once you have your first PR merged into the repo this won't be an issue as GitHub seems to auto-run after that.

**Comment by krishnaindani** [comment]
> @krishnaindani done, I'll keep an eye on this PR and keep clicking on the Approve workflow, once you have your first PR merged into the repo this won't be an issue as GitHub seems to auto-run after that.

sounds good. Thanks. I see this error `ineffectual assignment to `licenseType` (ineffassign)` in the lint stage, I guess I haven't changed anything on that line. It is coming from https://github.com/infracost/infracost/blob/master/internal/providers/terraform/azure/mssql_database.go#L202 looks like. Do I need to fix it?

**Comment by krishnaindani** [comment]
> > @krishnaindani done, I'll keep an eye on this PR and keep clicking on the Approve workflow, once you have your first PR merged into the repo this won't be an issue as GitHub seems to auto-run after that.
> 
> sounds good. Thanks. I see this error `ineffectual assignment to `licenseType` (ineffassign)` in the lint stage, I guess I haven't changed anything on that line. It is coming from https://github.com/infracost/infracost/blob/master/internal/providers/terraform/azure/mssql_database.go#L202 looks like. Do I need to fix it?

I think I got it, I messed up while fixing merge conflicts. I will go through the provider's directory once again to see If I missed anyplace as some new commits were introduced and I had changes from few days.

**Comment by alikhajeh1** [comment]
Thanks @krishnaindani - it looks like some of the tests are failing, the CI pipeline just runs these in case you'd like to run them locally to test things. For Azure, creds are needed to run Terraform - [this section](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#azure) explains how to get them (if that's not possible for you, I can provide  temporary read-only creds for you)..

```
make test_aws
make test_google
make test_azure
```

**Comment by krishnaindani** [comment]
> Thanks @krishnaindani - it looks like some of the tests are failing, the CI pipeline just runs these in case you'd like to run them locally to test things. For Azure, creds are needed to run Terraform - [this section](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#azure) explains how to get them (if that's not possible for you, I can provide temporary read-only creds for you)..
> 
> ```
> make test_aws
> make test_google
> make test_azure
> ```

The azure tests look okay, I will go through the one for aws and google and see where those are failing. Thank you

**Comment by alikhajeh1** [comment]
> The azure tests look okay, I will go through the one for aws and google and see where those are failing. Thank you

Thanks for taking initiative to fix this, it's a big PR! ping me if I can help with any of the failing tests :)

**Comment by krishnaindani** [comment]
I got caught up with something else past 3-4 days. Will be looking into fixing it this week.

**Comment by krishnaindani** [comment]
I have messed up something in my fork that I have. I will create a new fresh PR at the same time will test out everything. Closing out this pr and will be opening a new one very soon.

**Pull request closed without merging**
