### PR TITLE
Feat: (AWS) Adds support for ARM architectures

### PR DESCRIPTION
**Pull request by robh007**
Lambda resource would always provide cost estimates for x86 only. ARM architecture as a different cost tiers. Also fixed a bug where request usage wasn't being set at all. So whatever you set for requests it would never report the cost. 

Fixes part of #2138

### CODE REVIEW

**Comment by aliscott** [comment]
@robh007 thanks 🙏 , Can you try regenerating the golden file tests? It looks like the sync usage functionality is messing with it, so maybe try in a shell that doesn't have any `AWS_PROFILE` exported.

**Comment by robh007** [comment]
I've ran the `make test_update_usage`, not sure if these are required but the azure files have updated for some reason.

**Comment by robh007** [comment]
@aliscott not sure what's going on here. `TestWAFWebACLGoldenFile` Looks to be failing, I've ran the updated the AWS golden files too.

**Review by aliscott — APPROVED** [review]

**Comment by aliscott** [comment]
@robh007, thanks 🙏 ! I've looked through this and the test failures and it all seems unrelated. Will look into fixing up all the tests on master.

**Pull request merged**
