### PR TITLE
feat(google): add compute_vpn_tunnel support

### LINKED ISSUE #470: Add support for Google VPNs
Terraform resources:
`google_compute_vpn_gateway`
`google_compute_vpn_tunnel`
`google_compute_external_vpn_gateway`
`google_compute_ha_vpn_gateway`

Pricing page:
https://cloud.google.com/network-connectivity/docs/vpn/pricing

### PR DESCRIPTION
**Pull request by sinabakh**
Fix #470 

TODO:
- [x] `google_compute_vpn_tunnel`
- [x] `google_compute_vpn_gateway` and `google_compute_ha_vpn_gateway`
- [x] `google_compute_external_vpn_gateway`

### CODE REVIEW

**Comment by sinabakh** [comment]
@tim775 Regarding the `IPSecTraffic`, we can use the common `networkEgress` method. By default, it returns sub-resources and not cost components. However, using its cost components is easy. So we have two possible outputs:

Option 1 (default):
```
google_compute_external_vpn_gateway.external_gateway                                                              
 └─ Network egress                                                                                                 
    ├─ IPSec traffic to worldwide excluding Asia, Australia (first 1TB)                  1,024  GB         $122.88 
    ├─ IPSec traffic to worldwide excluding Asia, Australia (next 9TB)                   9,216  GB       $1,013.76 
    ├─ IPSec traffic to worldwide excluding Asia, Australia (over 10TB)                  2,260  GB         $180.80 
    ├─ IPSec traffic to Asia excluding China, but including Hong Kong (first 1TB)        1,024  GB         $122.88 
    ├─ IPSec traffic to Asia excluding China, but including Hong Kong (next 9TB)           476  GB          $52.36 
    ├─ IPSec traffic to China excluding Hong Kong (first 1TB)                               50  GB          $11.50 
    └─ IPSec traffic to Australia (first 1TB)                                              250  GB          $47.50 
```

Option 2:
```
google_compute_external_vpn_gateway.external_gateway                                                           
 ├─ IPSec traffic to worldwide excluding Asia, Australia (first 1TB)                  1,024  GB         $122.88 
 ├─ IPSec traffic to worldwide excluding Asia, Australia (next 9TB)                   9,216  GB       $1,013.76 
 ├─ IPSec traffic to worldwide excluding Asia, Australia (over 10TB)                  2,260  GB         $180.80 
 ├─ IPSec traffic to Asia excluding China, but including Hong Kong (first 1TB)        1,024  GB         $122.88 
 ├─ IPSec traffic to Asia excluding China, but including Hong Kong (next 9TB)           476  GB          $52.36 
 ├─ IPSec traffic to China excluding Hong Kong (first 1TB)                               50  GB          $11.50 
 └─ IPSec traffic to Australia (first 1TB)                                              250  GB          $47.50
```

I personally think the second option makes more sense but the first one is more compatible with few other resources with egress pricing. What do you think?

**Comment by tim775** [comment]
I don't have a strong opinion but I would go for option 1 since that is consistent with how we show egress for the existing google resources.

One thing I did notice though is that Cloud Storage egress (https://cloud.google.com/storage/pricing#network-egress) uses a slightly different table than VPC egress (https://cloud.google.com/vpc/network-pricing#internet_egress).  It looks like the prices are effectively the same, but VPC doesn't have `traffic to Asia` separate from `worldwide`.  

There are also separate pricing records for VPN:
```
> db.products.distinct("attributes.resourceGroup", {"vendorName": "gcp", "service": "Compute Engine", "productFamily": "Network" });
[
        ...,
	"VPNInternetEgress",
	"VPNInternetIngress",
	"VPNInterregionEgress",
	"VPNInterregionIngress",
	"VPNTunnel"
]
```
So I wasn't sure if we can refactor `network_egress` to let you specify which price records to use.  Or maybe it's good enough to just use the `Cloud Storage` pricing for all egress and deal with it if the prices ever diverge.  

@alikhajeh1 any thoughts?

**Comment by alikhajeh1** [comment]
> So I wasn't sure if we can refactor network_egress to let you specify which price records to use. Or maybe it's good enough to just use the Cloud Storage pricing for all egress and deal with it if the prices ever diverge.

Using Cloud Storage pricing is good enough just now, plz add a comment in the code to explain this though :)

**Comment by sinabakh** [comment]
I did some minor refactoring for `cloud storage egress` to make it more dynamic so we can continue with it for now. I will probably continue to make it a fully dynamic one in another PR.

**Comment by sinabakh** [comment]
It's finally done, I did some heavy refactoring on `network egress` and moved it to its separate file so we can use it for any kind of egress. The comments of @tim775 regarding the deficiencies are also resolved in this new version. 

Here's a sample output for all added resources:
```
 Name                                                                                             Monthly Qty  Unit   Monthly Cost 
                                                                                                                                   
 google_compute_external_vpn_gateway.my_compute_external_vpn_gateway                                                               
 └─ Network egress                                                                                                                 
    ├─ IPSec traffic to worldwide excluding China, Australia but including Hong Kong (first 1TB)        1,024  GB          $122.88 
    ├─ IPSec traffic to worldwide excluding China, Australia but including Hong Kong (next 9TB)         9,216  GB        $1,013.76 
    ├─ IPSec traffic to worldwide excluding China, Australia but including Hong Kong (over 10TB)        2,260  GB          $180.80 
    ├─ IPSec traffic to China excluding Hong Kong (first 1TB)                                           1,024  GB          $235.52 
    ├─ IPSec traffic to China excluding Hong Kong (next 9TB)                                            7,476  GB        $1,644.72 
    └─ IPSec traffic to Australia (first 1TB)                                                             250  GB           $47.50 
                                                                                                                                   
 google_compute_ha_vpn_gateway.my_compute_ha_vpn_gateway                                                                           
 └─ Network egress                                                                                                                 
    ├─ IPSec traffic within the same region                                                               250  GB            $2.50 
    ├─ IPSec traffic within the US or Canada                                                              100  GB            $1.00 
    ├─ IPSec traffic within Europe                                                                         70  GB            $1.40 
    ├─ IPSec traffic within Asia                                                                           50  GB            $2.50 
    ├─ IPSec traffic within South America                                                                 100  GB            $8.00 
    ├─ IPSec traffic to/from Indonesia and Oceania                                                         50  GB            $7.50 
    └─ IPSec traffic between continents (excludes Oceania)                                                200  GB           $16.00 
                                                                                                                                   
 google_compute_vpn_gateway.my_compute_vpn_gateway                                                                                 
 └─ Network egress                                                                                                                 
    ├─ IPSec traffic within the same region                                                               250  GB            $2.50 
    ├─ IPSec traffic within the US or Canada                                                              100  GB            $1.00 
    ├─ IPSec traffic within Europe                                                                         70  GB            $1.40 
    ├─ IPSec traffic within Asia                                                                           50  GB            $2.50 
    ├─ IPSec traffic within South America                                                                 100  GB            $8.00 
    ├─ IPSec traffic to/from Indonesia and Oceania                                                         50  GB            $7.50 
    └─ IPSec traffic between continents (excludes Oceania)                                                200  GB           $16.00 
                                                                                                                                   
 google_compute_vpn_tunnel.my_compute_vpn_tunnel                                                                                   
 └─ VPN Tunnel                                                                                            730  hours        $36.50 
                                                                                                                                   
 PROJECT TOTAL                                                                                                           $3,849.48 
```

**Comment by sinabakh** [comment]
Thanks, @tim775 for the review. That's a good point. I will work on it.

**Comment by sinabakh** [comment]
@alikhajeh1 Tested the prices with google calculator. All seem ok.

**Pull request merged**
