### PR TITLE
Add var terraform_json_plan

### PR DESCRIPTION
**Pull request by BoBiene**
- add variable terraform_json_plan
- add possiblity to source the script

### CODE REVIEW

**Comment by aliscott** [comment]
Thanks! For your use case is it possible to pass the terraform JSON file using the `path` variable or as the first argument to the script? I can see that we might want to add an alias for `path` since some shells don't differentiate this from `PATH`.

Allowing the script to be sourced is a great idea. Interested in knowing what the use case is? Are you adding customization before or after?

As a heads up/side note:
We've been migrating our [GitHub integrations](https://www.infracost.io/docs/guides/actions_migration/) and [GitLab integrations](https://www.infracost.io/docs/guides/gitlab_ci_migration/) to drop this diff script, in an effort to make the integrations more composable, (Azure DevOps is next).

**Review by eleazar-harold-zen — APPROVED** [review]
lgtm

**Comment by aliscott** [comment]
@BoBiene any thoughts on https://github.com/infracost/infracost/pull/1264#issuecomment-1005502463 if you have a chance?

**Comment by BoBiene** [comment]
@aliscott i have no clue about your `PATH` suggestions.

Regarding the usage: i needed access to some of the variables after processing (path of the json file) so i was the easiest implementation for me to just also use a variable to set the terraform plan file.

**Comment by aliscott** [comment]
@BoBiene thanks is it the Infracost JSON file you are needing to process after? 

Also, which CI platform are you using? Our new [GitHub integrations](https://www.infracost.io/docs/guides/actions_migration/) and [GitLab integrations](https://www.infracost.io/docs/guides/gitlab_ci_migration/) allow for this to be composable to you can easily run things against the Infracost JSON file afterwards.

If those aren't suitable then I think the change to source the file makes sense, but we'd probably also need to update this to not cleanup the `infracost_breakdown.json` file in this case.

**Comment by BoBiene** [comment]
Exactly, in need the infracost cost JSON output and want to use the terraform plan as input.
I'm using Azure DevOps.

this is my currently usage:
````bash
. ./infra-diff.sh 
echo "$breakdown_output" > $(System.DefaultWorkingDirectory)/output/cost.json
past_total_monthly_cost=$(jq '[.projects[].pastBreakdown.totalMonthlyCost | select (.!=null) | tonumber] | add' $(System.DefaultWorkingDirectory)/output/cost.json)
total_monthly_cost=$(jq '[.projects[].breakdown.totalMonthlyCost | select (.!=null) | tonumber] | add' $(System.DefaultWorkingDirectory)/output/cost.json)
diff_cost=$(jq '[.projects[].diff.totalMonthlyCost | select (.!=null) | tonumber] | add' $(System.DefaultWorkingDirectory)/output/cost.json)
````

**Comment by aliscott** [comment]
Thanks @BoBiene. One of our goals by the end of this month (January) is to release a better Azure DevOps integration (https://github.com/infracost/infracost-azure-devops/issues/4). The approach we're developing just now is a `SetupInfracost` task, which will install the `infracost` binary in your pipeline so you'll be able to run something like:

```yml
      - task: InfracostSetup@1
        displayName: Setup Infracost
        inputs:
          apiKey: $(apiKey)

      - bash: |
          infracost breakdown --path=examples/private-terraform-module/code --format=json --out-file=$(System.DefaultWorkingDirectory)/output/cost.json
          ... <any custom commands> ...
        displayName: Run Infracost
        
      - task: InfracostComment@1
        displayName: Post the comment
        inputs:
          path: infracost.json
          behavior: update # Create a single comment and update it
```

Do you think this would work for your use-case?

**Comment by BoBiene** [comment]
Looks good, would it be possible to export the summary variables past_total_monthly_cost, total_monthly_cost and diff_cost?
To implement an "auto approve" like here: https://www.mediaglasses.blog/2021/06/08/azure-devops-terraform-pipeline-with-checkov-approvals/

````bash
 if [ -z "$percent" ]; then
    echo "##vso[task.logissue type=warning]💰 - ℹ️ No previous cost data has been detected"
elif [ $(echo "$percent > $percentage_threshold" | bc -l) = 1 ]; then
    echo "##vso[task.logissue type=warning]💰 - 📈 A $percent% increase in cost have be detected. Your monthly costs are increasing from \$$past_total_monthly_cost to \$$total_monthly_cost"
    echo "##vso[task.setvariable variable=TERRAFORM_PLAN_HAS_DESTROY_CHANGES]true"
else
    echo "##vso[task.logissue type=warning]💰 - 📉 An acceptable or no change in cost has been detected. Your new monthly costs are \$$total_monthly_cost from \$$past_total_monthly_cost"
fi
````

image

**Comment by hugorut** [comment]
hey @BoBiene, I'm currently working on this scenario in the new Azure Devops Tasks integration. To answer your request/question, yes we want to allow users to export and use these variables in the pipeline. However, right now we're keeping these options flexible, allowing users to pick and choose which variables they want to export. Here's a simple example of what your auto approve step might look like:

```
jobs:
  - job: terraform_auto_approve
    displayName: Terraform  - Auto Approve
    pool:
      vmImage: ubuntu-latest

    steps:
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(apiKey)

      - bash: |
           infracost breakdown --path=examples/thresholds/code/plan.json --format=json --out-file=/tmp/infracost.json 
           
           # Read the breakdown JSON and get costs
           cost_change=$(cat /tmp/infracost.json | jq -r "(.diffTotalMonthlyCost // 0) | tonumber")
           echo "##vso[task.setvariable variable=costChange;]${cost_change}"
        displayName: Run Infracost

      - bash: terraform apply --auto-approve
        displayName: Terraform approve
        condition: gt(variables.costChange, 100) # Only approve if cost increased by more than $100
```

Now we're aware that working with the `infracost.json` directly in bash isn't the nicest experience. We are still strategising the best options for this and also looking at how we improve our JSON output to be more user friendly, see discussion here: https://github.com/infracost/infracost/discussions/1278

With the new JSON v2 format extracting `cost_change` would just look like so:

```
cost_change=$(cat /tmp/infracost.json | jq -r ".diffTotalMonthlyCost")
 ```
 
Are these examples/ideas something that would work for your usecase or do you think we need to add something more? Do you have any suggestions that could make your life easier?

**Comment by aliscott** [comment]
@BoBiene @hugorut should we close this since it looks like this functionality will be possible in the new Azure integration we're releasing soon?

**Comment by BoBiene** [comment]
Yes, you can close this.

**Comment by aliscott** [comment]
Thanks @BoBiene we'll ping you here when it's released!

**Comment by hugorut** [comment]
Hey @BoBiene we've just released this and you can install the Infracost tasks into your org using our shiny new extension: https://marketplace.visualstudio.com/items?itemName=Infracost.infracost-tasks

**Pull request closed without merging**
